# Generated by Django 5.2.13 on 2026-05-02 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='ocr_uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('raw_text', models.TextField(blank=True)),
                ('candidate_ids', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('set_id', models.CharField(blank=True, max_length=64)),
                ('set_name', models.CharField(blank=True, max_length=255)),
                ('set_series', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=64)),
                ('rarity', models.CharField(blank=True, max_length=128)),
                ('image_small_url', models.URLField(blank=True)),
                ('image_large_url', models.URLField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cardmarket_url', models.URLField(blank=True)),
                ('latest_price_payload', models.JSONField(blank=True, default=dict)),
                ('api_updated_at', models.CharField(blank=True, max_length=64)),
                ('api_synced_at', models.DateTimeField(blank=True, null=True)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_source_field', models.CharField(blank=True, max_length=64)),
                ('price_currency', models.CharField(default='EUR', max_length=3)),
                ('price_upstream_updated_at', models.DateField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['set_name', 'card_number', 'name'],
                'indexes': [models.Index(fields=['name'], name='collection__name_fb8ea1_idx'), models.Index(fields=['set_name', 'card_number'], name='collection__set_nam_d0d3ff_idx'), models.Index(fields=['set_id'], name='collection__set_id_85f76a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('normal', 'Normal'), ('holofoil', 'Holofoil'), ('reverse_holofoil', 'Reverse holofoil'), ('first_edition_normal', 'First edition normal'), ('first_edition_holofoil', 'First edition holofoil'), ('unknown', 'Unknown'), ('custom', 'Custom')], default='normal', max_length=32)),
                ('variant_custom', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(default='en', max_length=16, validators=[django.core.validators.RegexValidator(message='Use a short language code such as en, de, or pt-BR.', regex='^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})?$')])),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('light_played', 'Light Played'), ('played', 'Played'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='near_mint', max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to='collection.cardmetadata')),
            ],
            options={
                'ordering': ['card__set_name', 'card__card_number', 'card__name', 'variant', 'condition'],
                'indexes': [models.Index(fields=['variant'], name='collection__variant_2b6fcb_idx'), models.Index(fields=['condition'], name='collection__conditi_b9ff16_idx'), models.Index(fields=['language'], name='collection__languag_6422a9_idx')],
            },
        ),
    ]
