# Generated by Django 5.2.13 on 2026-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('printed_total', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('symbol_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('api_updated_at', models.CharField(blank=True, max_length=64)),
                ('api_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_date', 'name'],
                'indexes': [models.Index(fields=['name'], name='collection__name_b6668c_idx'), models.Index(fields=['series'], name='collection__series_16bbc6_idx'), models.Index(fields=['release_date'], name='collection__release_7b8e40_idx')],
            },
        ),
    ]
