# Generated by Codex on 2026-05-03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_correct_known_cardmarket_mappings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedcard",
            name="language",
            field=models.CharField(
                default="de",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a short language code such as en, de, or pt-BR.",
                        regex="^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})?$",
                    )
                ],
            ),
        ),
    ]
